packages:
  - .
  - ui
  - packages/*
  - extensions/*
  - "!extensions/_matrix.disabled"

onlyBuiltDependencies:
  - '@whiskeysockets/baileys'
  - '@lydell/node-pty'
  - '@matrix-org/matrix-sdk-crypto-nodejs'
  - authenticate-pam
  - esbuild
  - protobufjs
  - sharp
